# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/azure-pipelines
- main

pool:
  vmImage: ubuntu-latest #windows-latest, macOS-latest

stages:
- stage: Validate
  displayName: 'Validation Stage'
  jobs:
  - job:
    displayName: 'Simple Job'
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
  - job:
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
- stage: Deploy
  jobs:
  - job:
    displayName: 'Deploy Job'
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
- stage: PostDeploy
  jobs:
  - job:
    displayName: 'Post-Deploy Job'
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'


