name: "Salesforce UAT Pipeline"
run-name: "Salesforce UAT Pipeline Run"

on:
    pull_request:
      types:
        - open
        - closed
      paths:
        - 'force-app/**'
      branches:
        - UAT

env:
  ORG_DEFAULT_ALIAS: UAT_ORG
  NODE_VERSION: ">=20.9.0"
  JAVA_VERSION: ">=11"
  SF_CLI_VERSION: latest
  ORG_VARIABLE: ${{ vars.ORGANIZATION_VARIABLE }}

jobs:
  build-salesforce: 
    name: "Build & Validate"
    uses: "./.github/workflows/template.yaml"
    with:
      envionment: UAT
      runner: macos-latest
    secrets: inherit
    #secrets: 
    #  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}